FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["WebIngest.WebAPI/WebIngest.WebAPI.csproj", "WebIngest.WebAPI/"]
RUN dotnet restore "WebIngest.WebAPI/WebIngest.WebAPI.csproj"
COPY . .
WORKDIR "/src/WebIngest.WebAPI"
RUN dotnet build "WebIngest.WebAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebIngest.WebAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebIngest.WebAPI.dll"]
